apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs7cs3-mariadb-pvc
  labels:
    app: cs7cs3-mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
